name: "Submit to Web Store"
on:
    workflow_run:
        workflows: ["Extension Release"]
        types:
            - completed

jobs:
    submit:
      runs-on: "ubuntu-latest"
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Compress Repository
          run: |
            zip -r extension-source.zip .

        - name: Download Release Artifacts
          uses: dawidd6/action-download-artifact@v2
          with:
            workflow: release.yml
            run_id: ${{ github.event.workflow_run.id }}
            path: artifacts

        - name: Chrome Web Store Publish
          uses: browser-actions/release-chrome-extension@v0.2.1
          with:
            extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
            extension-path: "artifacts/extension-*-chrome.zip"
            oauth-client-id: ${{ secrets.OAUTH_CLIENT_ID }}
            oauth-client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
            oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}