name: "Submit to Web Store"
on:
    workflow_run:
        workflows: ["Extension Release"]
        types:
            - completed

jobs:
    submit:
      runs-on: "ubuntu-latest"
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Compress Repository
          run: |
            zip -r extension-source.zip .

        - name: Download Release Assets
          uses: robinraju/release-downloader@v1
          with:
            latest: true
            out-file-path: "assets"
            fileName: '*'

        - name: Chrome Web Store Publish
          uses: browser-actions/release-chrome-extension@v0.2.1
          with:
            extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
            extension-path: "assets/extension-*-chrome.zip"
            oauth-client-id: ${{ secrets.OAUTH_CLIENT_ID }}
            oauth-client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
            oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}